// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: login.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IMLoginServiceClient is the client API for IMLoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IMLoginServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type iMLoginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIMLoginServiceClient(cc grpc.ClientConnInterface) IMLoginServiceClient {
	return &iMLoginServiceClient{cc}
}

func (c *iMLoginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/api.hotUpdate.v1.IMLoginService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMLoginServiceServer is the server API for IMLoginService service.
// All implementations must embed UnimplementedIMLoginServiceServer
// for forward compatibility
type IMLoginServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedIMLoginServiceServer()
}

// UnimplementedIMLoginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIMLoginServiceServer struct {
}

func (UnimplementedIMLoginServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedIMLoginServiceServer) mustEmbedUnimplementedIMLoginServiceServer() {}

// UnsafeIMLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMLoginServiceServer will
// result in compilation errors.
type UnsafeIMLoginServiceServer interface {
	mustEmbedUnimplementedIMLoginServiceServer()
}

func RegisterIMLoginServiceServer(s grpc.ServiceRegistrar, srv IMLoginServiceServer) {
	s.RegisterService(&IMLoginService_ServiceDesc, srv)
}

func _IMLoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMLoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.hotUpdate.v1.IMLoginService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMLoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMLoginService_ServiceDesc is the grpc.ServiceDesc for IMLoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMLoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.hotUpdate.v1.IMLoginService",
	HandlerType: (*IMLoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _IMLoginService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}
