// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"git.vfeda.com/vfedabackendteam/jimuhotupdate/internal/pkg/data"
	"git.vfeda.com/vfedabackendteam/jimuhotupdate/internal/server/repo"
	"git.vfeda.com/vfedabackendteam/jimuhotupdate/internal/server/service"
	"git.vfeda.com/vfedabackendteam/jimuhotupdate/internal/server/usecase"
)

// Injectors from wire.go:

func NewServices() (*services, error) {
	db := data.InitDB()
	iUserRepo := repo.NewUserRepo(db)
	iUserUseCase := usecase.NewUserUseCase(iUserRepo)
	userService := service.NewUserService(iUserUseCase)
	mainServices := &services{
		u: userService,
	}
	return mainServices, nil
}
